//! Generated cubemap environments for analytic skybox materials.

use std::borrow::Cow;
use std::collections::HashMap;
use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};
use std::sync::Arc;

use bytemuck::{Pod, Zeroable};
use thiserror::Error;
use wgpu::util::DeviceExt;

use crate::backend::frame_gpu::{
    SkyboxSpecularEnvironmentSource, SkyboxSpecularGeneratedCubemapSource,
};
use crate::embedded_shaders;
use crate::gpu::{GpuContext, GpuLimits};
use crate::gpu_pools::SamplerState;
use crate::materials::host_data::MaterialPropertyLookupIds;
use crate::scene::SceneCoordinator;
use crate::shared::{TextureFilterMode, TextureWrapMode};
use crate::skybox::params::{
    DEFAULT_GENERATED_SKYBOX_FACE_SIZE, gradient_sky_params, procedural_sky_params,
};

use crate::backend::gpu_jobs::{GpuJobResources, GpuSubmitJobTracker, SubmittedGpuJob};

/// Maximum generated skybox bake jobs allowed in flight at once.
const MAX_IN_FLIGHT_SKYBOX_BAKES: usize = 2;
/// Number of renderer ticks before a skybox bake completion callback is treated as lost.
const MAX_PENDING_SKYBOX_BAKE_AGE_FRAMES: u32 = 120;
/// Generated cubemap format used by analytic skybox bake compute.
const GENERATED_SKYBOX_FORMAT: wgpu::TextureFormat = wgpu::TextureFormat::Rgba16Float;
/// Compute workgroup edge used by skybox bake and mip generation shaders.
const SKYBOX_WORKGROUP_EDGE: u32 = 8;
/// GGX samples evaluated per generated roughness mip texel.
const SKYBOX_PREFILTER_SAMPLE_COUNT: u32 = 64;

/// Uniform payload for one generated cubemap roughness prefilter pass.
#[repr(C)]
#[derive(Clone, Copy, Debug, Pod, Zeroable)]
struct PrefilterParams {
    /// Destination mip face edge.
    dst_size: u32,
    /// Destination mip index being generated.
    mip_index: u32,
    /// Total mip count in the generated cubemap.
    mip_count: u32,
    /// Number of GGX importance samples to evaluate per texel.
    sample_count: u32,
}

/// Errors returned while preparing skybox bake GPU work.
#[derive(Debug, Error)]
enum SkyboxEnvironmentBakeError {
    /// Embedded WGSL source was not available.
    #[error("embedded shader {0} not found")]
    MissingShader(&'static str),
}

/// Identity for one generated skybox cubemap.
#[derive(Clone, Debug, Eq, PartialEq, Hash)]
struct GeneratedSkyboxKey {
    /// Active skybox material asset id.
    material_asset_id: i32,
    /// Material property generation used to invalidate baked results.
    material_generation: u64,
    /// Shader route hash so material shader changes invalidate baked results.
    route_hash: u64,
    /// Generated cubemap mip0 face size.
    face_size: u32,
}

impl GeneratedSkyboxKey {
    /// Returns a stable renderer-local hash for frame-global binding keys.
    fn source_hash(&self) -> u64 {
        let mut hasher = DefaultHasher::new();
        self.hash(&mut hasher);
        hasher.finish()
    }
}

/// Resolved active skybox bake request.
struct SkyboxBakeRequest {
    /// Generated cubemap identity.
    key: GeneratedSkyboxKey,
    /// Packed material evaluator parameters for the bake shader.
    params: crate::skybox::params::SkyboxEvaluatorParams,
}

/// Completed generated skybox cubemap ready for frame-global specular binding.
struct GeneratedSkyboxEnvironment {
    /// Texture backing the generated cube view.
    _texture: Arc<wgpu::Texture>,
    /// Full mip-chain cube view.
    view: Arc<wgpu::TextureView>,
    /// Sampler fields used when building the frame-global sampler.
    sampler: SamplerState,
    /// Mip count generated by the bake job.
    mip_levels: u32,
}

/// Texture handles created for one generated skybox bake.
struct GeneratedSkyboxTexture {
    /// Texture backing the generated cube view.
    texture: Arc<wgpu::Texture>,
    /// Full mip-chain cube view.
    full_view: Arc<wgpu::TextureView>,
}

impl GeneratedSkyboxEnvironment {
    /// Converts the generated cubemap into a frame-global specular source.
    fn to_specular_source(&self, key: &GeneratedSkyboxKey) -> SkyboxSpecularEnvironmentSource {
        SkyboxSpecularEnvironmentSource::GeneratedCubemap(SkyboxSpecularGeneratedCubemapSource {
            key_hash: key.source_hash(),
            view: self.view.clone(),
            sampler: self.sampler.clone(),
            mip_levels_resident: self.mip_levels,
            storage_v_inverted: false,
        })
    }
}

/// Generated cubemap plus transient resources retained until submit completion.
struct PendingGeneratedSkybox {
    /// Completed environment that becomes visible after submit completion.
    environment: GeneratedSkyboxEnvironment,
    /// Transient resources retained until the queued commands complete.
    _resources: PendingBakeResources,
}

/// Transient command resources that must survive until submit completion.
#[derive(Default)]
struct PendingBakeResources {
    /// Uniform and transient buffers retained until the queued commands complete.
    buffers: Vec<wgpu::Buffer>,
    /// Bind groups retained until the queued commands complete.
    bind_groups: Vec<wgpu::BindGroup>,
    /// One-mip texture views retained until the queued commands complete.
    texture_views: Vec<wgpu::TextureView>,
}

/// Lazily-created compute pipeline and bind-group layout.
struct ComputePipelineWithLayout {
    /// Compute pipeline.
    pipeline: wgpu::ComputePipeline,
    /// Bind-group layout for this pipeline.
    layout: wgpu::BindGroupLayout,
}

/// Inputs needed to encode the mip-zero analytic bake pass.
struct BakeMip0EncodeContext<'a> {
    /// Device used for buffer and bind group creation.
    device: &'a wgpu::Device,
    /// Command encoder receiving compute work.
    encoder: &'a mut wgpu::CommandEncoder,
    /// Compute pipeline for the bake shader.
    pipeline: &'a ComputePipelineWithLayout,
    /// Generated cubemap texture.
    texture: &'a wgpu::Texture,
    /// Packed skybox evaluator parameters.
    params: &'a crate::skybox::params::SkyboxEvaluatorParams,
    /// Cubemap face edge for mip zero.
    face_size: u32,
}

/// Inputs needed to encode generated cubemap roughness prefiltering.
struct PrefilterEncodeContext<'a> {
    /// Device used for buffer and bind group creation.
    device: &'a wgpu::Device,
    /// Command encoder receiving compute work.
    encoder: &'a mut wgpu::CommandEncoder,
    /// Compute pipeline for the prefilter shader.
    pipeline: &'a ComputePipelineWithLayout,
    /// Generated cubemap texture.
    texture: &'a wgpu::Texture,
    /// Packed skybox evaluator parameters.
    params: &'a crate::skybox::params::SkyboxEvaluatorParams,
    /// Total mip count in the generated cubemap.
    mip_levels: u32,
}

/// Owns generated skybox environment bakes and completed cubemap cache entries.
pub(crate) struct SkyboxEnvironmentCache {
    /// Submit-completion tracker for in-flight bake command buffers.
    jobs: GpuSubmitJobTracker<GeneratedSkyboxKey>,
    /// In-flight generated cubemaps retained until their submit callback fires.
    pending: HashMap<GeneratedSkyboxKey, PendingGeneratedSkybox>,
    /// Completed generated cubemaps keyed by active material identity.
    completed: HashMap<GeneratedSkyboxKey, GeneratedSkyboxEnvironment>,
    /// Lazily-created procedural/gradient bake pipeline.
    bake_pipeline: Option<ComputePipelineWithLayout>,
    /// Lazily-created roughness prefilter pipeline.
    prefilter_pipeline: Option<ComputePipelineWithLayout>,
}

impl Default for SkyboxEnvironmentCache {
    fn default() -> Self {
        Self::new()
    }
}

impl SkyboxEnvironmentCache {
    /// Creates an empty generated skybox environment cache.
    pub(crate) fn new() -> Self {
        Self {
            jobs: GpuSubmitJobTracker::new(MAX_PENDING_SKYBOX_BAKE_AGE_FRAMES),
            pending: HashMap::new(),
            completed: HashMap::new(),
            bake_pipeline: None,
            prefilter_pipeline: None,
        }
    }

    /// Advances bake completions and schedules the active analytic skybox if needed.
    pub(crate) fn maintain(
        &mut self,
        gpu: &GpuContext,
        scene: &SceneCoordinator,
        materials: &crate::materials::MaterialSystem,
    ) {
        profiling::scope!("skybox_environment::maintain");
        let _ = gpu.device().poll(wgpu::PollType::Poll);
        self.drain_completed_jobs();
        let active = resolve_active_bake_request(scene, materials, gpu.limits());
        self.prune_completed(active.as_ref().map(|request| &request.key));
        let Some(request) = active else {
            return;
        };
        if self.completed.contains_key(&request.key)
            || self.pending.contains_key(&request.key)
            || self.jobs.contains_key(&request.key)
            || self.jobs.len() >= MAX_IN_FLIGHT_SKYBOX_BAKES
        {
            return;
        }
        match self.schedule_bake(gpu, request) {
            Ok(()) => {}
            Err(e) => logger::warn!("skybox_environment: generated cubemap bake failed: {e}"),
        }
    }

    /// Resolves the active generated skybox cubemap, if a completed one is available.
    pub(crate) fn active_specular_source(
        &self,
        scene: &SceneCoordinator,
        materials: &crate::materials::MaterialSystem,
        limits: &GpuLimits,
    ) -> Option<SkyboxSpecularEnvironmentSource> {
        let request = resolve_active_bake_request(scene, materials, limits)?;
        self.completed
            .get(&request.key)
            .map(|environment| environment.to_specular_source(&request.key))
    }

    /// Moves submit-completed bake results into the completed cache.
    fn drain_completed_jobs(&mut self) {
        let outcomes = self.jobs.maintain();
        for key in outcomes.completed {
            if let Some(pending) = self.pending.remove(&key) {
                self.completed.insert(key, pending.environment);
            }
        }
        for key in outcomes.failed {
            self.pending.remove(&key);
            logger::warn!("skybox_environment: generated cubemap bake expired before completion");
        }
    }

    /// Drops completed entries that cannot be used by the current active skybox.
    fn prune_completed(&mut self, active: Option<&GeneratedSkyboxKey>) {
        self.completed
            .retain(|key, _| active.is_some_and(|active_key| active_key == key));
    }

    /// Encodes and submits one generated cubemap bake.
    fn schedule_bake(
        &mut self,
        gpu: &GpuContext,
        request: SkyboxBakeRequest,
    ) -> Result<(), SkyboxEnvironmentBakeError> {
        self.ensure_pipelines(gpu.device())?;
        let bake_pipeline = self.bake_pipeline()?;
        let prefilter_pipeline = self.prefilter_pipeline()?;
        let face_size = request.key.face_size;
        let mip_levels = mip_levels_for_edge(face_size);
        let texture = create_generated_skybox_texture(gpu.device(), face_size, mip_levels);
        let mut resources = PendingBakeResources::default();
        let mut encoder = gpu
            .device()
            .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                label: Some("generated skybox bake encoder"),
            });
        encode_mip0_bake(
            BakeMip0EncodeContext {
                device: gpu.device(),
                encoder: &mut encoder,
                pipeline: bake_pipeline,
                texture: texture.texture.as_ref(),
                params: &request.params,
                face_size,
            },
            &mut resources,
        );
        encode_prefilter_mips(
            PrefilterEncodeContext {
                device: gpu.device(),
                encoder: &mut encoder,
                pipeline: prefilter_pipeline,
                texture: texture.texture.as_ref(),
                params: &request.params,
                mip_levels,
            },
            &mut resources,
        );
        let pending = make_pending_generated_skybox(texture, resources, mip_levels);
        self.submit_pending_bake(gpu, request.key, encoder, pending);
        Ok(())
    }

    /// Ensures both skybox bake compute pipelines are resident.
    fn ensure_pipelines(
        &mut self,
        device: &wgpu::Device,
    ) -> Result<(), SkyboxEnvironmentBakeError> {
        let _ = ensure_pipeline(
            &mut self.bake_pipeline,
            device,
            "skybox_bake_params",
            &bake_layout_entries(),
        )?;
        let _ = ensure_pipeline(
            &mut self.prefilter_pipeline,
            device,
            "skybox_prefilter_params",
            &prefilter_layout_entries(),
        )?;
        Ok(())
    }

    /// Returns the resident skybox bake pipeline.
    fn bake_pipeline(&self) -> Result<&ComputePipelineWithLayout, SkyboxEnvironmentBakeError> {
        self.bake_pipeline
            .as_ref()
            .ok_or(SkyboxEnvironmentBakeError::MissingShader(
                "skybox_bake_params",
            ))
    }

    /// Returns the resident skybox roughness prefilter pipeline.
    fn prefilter_pipeline(&self) -> Result<&ComputePipelineWithLayout, SkyboxEnvironmentBakeError> {
        self.prefilter_pipeline
            .as_ref()
            .ok_or(SkyboxEnvironmentBakeError::MissingShader(
                "skybox_prefilter_params",
            ))
    }

    /// Tracks and submits an encoded generated skybox bake.
    fn submit_pending_bake(
        &mut self,
        gpu: &GpuContext,
        key: GeneratedSkyboxKey,
        encoder: wgpu::CommandEncoder,
        pending: PendingGeneratedSkybox,
    ) {
        let tx = self.jobs.submit_done_sender();
        let callback_key = key.clone();
        self.jobs.insert(
            key.clone(),
            SubmittedGpuJob {
                resources: GpuJobResources::new(),
            },
        );
        self.pending.insert(key, pending);
        gpu.submit_frame_batch_with_callbacks(
            vec![encoder.finish()],
            None,
            None,
            vec![Box::new(move || {
                let _ = tx.send(callback_key);
            })],
        );
    }
}

/// Creates the generated cubemap texture and its full cube sampling view.
fn create_generated_skybox_texture(
    device: &wgpu::Device,
    face_size: u32,
    mip_levels: u32,
) -> GeneratedSkyboxTexture {
    let texture = Arc::new(device.create_texture(&wgpu::TextureDescriptor {
        label: Some("generated_skybox_environment_cube"),
        size: wgpu::Extent3d {
            width: face_size,
            height: face_size,
            depth_or_array_layers: 6,
        },
        mip_level_count: mip_levels,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: GENERATED_SKYBOX_FORMAT,
        usage: wgpu::TextureUsages::TEXTURE_BINDING
            | wgpu::TextureUsages::STORAGE_BINDING
            | wgpu::TextureUsages::COPY_SRC,
        view_formats: &[],
    }));
    let full_view = Arc::new(texture.create_view(&wgpu::TextureViewDescriptor {
        label: Some("generated_skybox_environment_cube_view"),
        format: Some(GENERATED_SKYBOX_FORMAT),
        dimension: Some(wgpu::TextureViewDimension::Cube),
        usage: Some(wgpu::TextureUsages::TEXTURE_BINDING),
        aspect: wgpu::TextureAspect::All,
        base_mip_level: 0,
        mip_level_count: Some(mip_levels),
        base_array_layer: 0,
        array_layer_count: Some(6),
    }));
    GeneratedSkyboxTexture { texture, full_view }
}

/// Creates the pending cache entry for a submitted generated skybox bake.
fn make_pending_generated_skybox(
    texture: GeneratedSkyboxTexture,
    resources: PendingBakeResources,
    mip_levels: u32,
) -> PendingGeneratedSkybox {
    PendingGeneratedSkybox {
        environment: GeneratedSkyboxEnvironment {
            _texture: texture.texture,
            view: texture.full_view,
            sampler: generated_environment_sampler_state(),
            mip_levels,
        },
        _resources: resources,
    }
}

/// Returns the sampler state used when generated cubemaps are bound for material sampling.
fn generated_environment_sampler_state() -> SamplerState {
    SamplerState {
        filter_mode: TextureFilterMode::Trilinear,
        aniso_level: 1,
        wrap_u: TextureWrapMode::Clamp,
        wrap_v: TextureWrapMode::Clamp,
        wrap_w: TextureWrapMode::default(),
        mipmap_bias: 0.0,
    }
}

/// Resolves the active skybox material into a generated cubemap request.
fn resolve_active_bake_request(
    scene: &SceneCoordinator,
    materials: &crate::materials::MaterialSystem,
    limits: &GpuLimits,
) -> Option<SkyboxBakeRequest> {
    let material_asset_id = scene.active_main_space()?.skybox_material_asset_id;
    if material_asset_id < 0 {
        return None;
    }
    let store = materials.material_property_store();
    let shader_asset_id = store.shader_asset_for_material(material_asset_id)?;
    let route_name = shader_route_name(materials, shader_asset_id)?;
    let route_lower = route_name.to_ascii_lowercase();
    let lookup = MaterialPropertyLookupIds {
        material_asset_id,
        mesh_property_block_slot0: None,
    };
    let face_size = generated_face_size(limits);
    let mut params = if route_lower.contains("gradient") {
        gradient_sky_params(store, materials.property_id_registry(), lookup)
    } else if route_lower.contains("procedural") {
        procedural_sky_params(store, materials.property_id_registry(), lookup)
    } else {
        return None;
    };
    params = params.with_sample_size(face_size);
    Some(SkyboxBakeRequest {
        key: GeneratedSkyboxKey {
            material_asset_id,
            material_generation: store.material_generation(material_asset_id),
            route_hash: hash_route_name(&route_name),
            face_size,
        },
        params,
    })
}

/// Returns a shader route name or stem for a shader asset id.
fn shader_route_name(
    materials: &crate::materials::MaterialSystem,
    shader_asset_id: i32,
) -> Option<String> {
    let registry = materials.material_registry()?;
    registry
        .stem_for_shader_asset(shader_asset_id)
        .map(str::to_string)
}

/// Hashes a route name into a stable generated-cubemap discriminator.
fn hash_route_name(route: &str) -> u64 {
    let mut hasher = DefaultHasher::new();
    route.hash(&mut hasher);
    hasher.finish()
}

/// Clamps the configured generated face size to portable device limits.
fn generated_face_size(limits: &GpuLimits) -> u32 {
    DEFAULT_GENERATED_SKYBOX_FACE_SIZE
        .min(limits.max_texture_dimension_2d())
        .max(1)
}

/// Returns the full mip count for a power-of-two or non-power-of-two texture edge.
fn mip_levels_for_edge(edge: u32) -> u32 {
    u32::BITS - edge.max(1).leading_zeros()
}

/// Returns dispatch group count for one 8x8 compute dimension.
fn dispatch_groups(size: u32) -> u32 {
    size.max(1).div_ceil(SKYBOX_WORKGROUP_EDGE)
}

/// Ensures a compute pipeline exists for an embedded shader target.
fn ensure_pipeline<'a>(
    slot: &'a mut Option<ComputePipelineWithLayout>,
    device: &wgpu::Device,
    stem: &'static str,
    entries: &[wgpu::BindGroupLayoutEntry],
) -> Result<&'a ComputePipelineWithLayout, SkyboxEnvironmentBakeError> {
    if slot.is_none() {
        let source = embedded_shaders::embedded_target_wgsl(stem)
            .ok_or(SkyboxEnvironmentBakeError::MissingShader(stem))?;
        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some(stem),
            source: wgpu::ShaderSource::Wgsl(Cow::Borrowed(source)),
        });
        let layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some(&format!("{stem} bind group layout")),
            entries,
        });
        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some(&format!("{stem} pipeline layout")),
            bind_group_layouts: &[Some(&layout)],
            immediate_size: 0,
        });
        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some(stem),
            layout: Some(&pipeline_layout),
            module: &shader,
            entry_point: Some("main"),
            compilation_options: wgpu::PipelineCompilationOptions::default(),
            cache: None,
        });
        *slot = Some(ComputePipelineWithLayout { pipeline, layout });
    }
    slot.as_ref()
        .ok_or(SkyboxEnvironmentBakeError::MissingShader(stem))
}

/// Bind-group layout entries for the analytic skybox bake shader.
fn bake_layout_entries() -> [wgpu::BindGroupLayoutEntry; 2] {
    [
        wgpu::BindGroupLayoutEntry {
            binding: 0,
            visibility: wgpu::ShaderStages::COMPUTE,
            ty: wgpu::BindingType::Buffer {
                ty: wgpu::BufferBindingType::Uniform,
                has_dynamic_offset: false,
                min_binding_size: None,
            },
            count: None,
        },
        storage_texture_layout_entry(1),
    ]
}

/// Bind-group layout entries for the generated cubemap roughness prefilter shader.
fn prefilter_layout_entries() -> [wgpu::BindGroupLayoutEntry; 3] {
    [
        wgpu::BindGroupLayoutEntry {
            binding: 0,
            visibility: wgpu::ShaderStages::COMPUTE,
            ty: wgpu::BindingType::Buffer {
                ty: wgpu::BufferBindingType::Uniform,
                has_dynamic_offset: false,
                min_binding_size: None,
            },
            count: None,
        },
        wgpu::BindGroupLayoutEntry {
            binding: 1,
            visibility: wgpu::ShaderStages::COMPUTE,
            ty: wgpu::BindingType::Buffer {
                ty: wgpu::BufferBindingType::Uniform,
                has_dynamic_offset: false,
                min_binding_size: None,
            },
            count: None,
        },
        storage_texture_layout_entry(2),
    ]
}

/// Storage texture layout entry for a single 2D-array cubemap mip.
fn storage_texture_layout_entry(binding: u32) -> wgpu::BindGroupLayoutEntry {
    wgpu::BindGroupLayoutEntry {
        binding,
        visibility: wgpu::ShaderStages::COMPUTE,
        ty: wgpu::BindingType::StorageTexture {
            access: wgpu::StorageTextureAccess::WriteOnly,
            format: GENERATED_SKYBOX_FORMAT,
            view_dimension: wgpu::TextureViewDimension::D2Array,
        },
        count: None,
    }
}

/// Creates a storage view for one cubemap mip.
fn create_mip_storage_view(texture: &wgpu::Texture, mip: u32) -> wgpu::TextureView {
    texture.create_view(&wgpu::TextureViewDescriptor {
        label: Some("generated_skybox_mip_storage_view"),
        format: Some(GENERATED_SKYBOX_FORMAT),
        dimension: Some(wgpu::TextureViewDimension::D2Array),
        usage: Some(wgpu::TextureUsages::STORAGE_BINDING),
        aspect: wgpu::TextureAspect::All,
        base_mip_level: mip,
        mip_level_count: Some(1),
        base_array_layer: 0,
        array_layer_count: Some(6),
    })
}

/// Encodes the analytic skybox evaluator into mip zero of the generated cubemap.
fn encode_mip0_bake(ctx: BakeMip0EncodeContext<'_>, resources: &mut PendingBakeResources) {
    let params_buffer = ctx
        .device
        .create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("generated skybox params"),
            contents: bytemuck::bytes_of(ctx.params),
            usage: wgpu::BufferUsages::UNIFORM,
        });
    let mip0_storage = create_mip_storage_view(ctx.texture, 0);
    let bind_group = ctx.device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some("generated skybox bake bind group"),
        layout: &ctx.pipeline.layout,
        entries: &[
            wgpu::BindGroupEntry {
                binding: 0,
                resource: params_buffer.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 1,
                resource: wgpu::BindingResource::TextureView(&mip0_storage),
            },
        ],
    });
    {
        let mut pass = ctx
            .encoder
            .begin_compute_pass(&wgpu::ComputePassDescriptor {
                label: Some("generated skybox bake"),
                timestamp_writes: None,
            });
        pass.set_pipeline(&ctx.pipeline.pipeline);
        pass.set_bind_group(0, &bind_group, &[]);
        pass.dispatch_workgroups(
            dispatch_groups(ctx.face_size),
            dispatch_groups(ctx.face_size),
            6,
        );
    };
    resources.buffers.push(params_buffer);
    resources.bind_groups.push(bind_group);
    resources.texture_views.push(mip0_storage);
}

/// Encodes roughness-prefiltered mip generation after mip zero.
fn encode_prefilter_mips(ctx: PrefilterEncodeContext<'_>, resources: &mut PendingBakeResources) {
    if ctx.mip_levels <= 1 {
        return;
    }
    let sky_params_buffer = ctx
        .device
        .create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("generated skybox prefilter sky params"),
            contents: bytemuck::bytes_of(ctx.params),
            usage: wgpu::BufferUsages::UNIFORM,
        });
    for mip in 1..ctx.mip_levels {
        let dst_size = mip_extent(ctx.texture.size().width, mip);
        let params = PrefilterParams {
            dst_size,
            mip_index: mip,
            mip_count: ctx.mip_levels,
            sample_count: SKYBOX_PREFILTER_SAMPLE_COUNT,
        };
        let params_buffer = ctx
            .device
            .create_buffer_init(&wgpu::util::BufferInitDescriptor {
                label: Some("generated skybox prefilter params"),
                contents: bytemuck::bytes_of(&params),
                usage: wgpu::BufferUsages::UNIFORM,
            });
        let dst_view = create_mip_storage_view(ctx.texture, mip);
        let bind_group = ctx.device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("generated skybox prefilter bind group"),
            layout: &ctx.pipeline.layout,
            entries: &[
                wgpu::BindGroupEntry {
                    binding: 0,
                    resource: sky_params_buffer.as_entire_binding(),
                },
                wgpu::BindGroupEntry {
                    binding: 1,
                    resource: params_buffer.as_entire_binding(),
                },
                wgpu::BindGroupEntry {
                    binding: 2,
                    resource: wgpu::BindingResource::TextureView(&dst_view),
                },
            ],
        });
        {
            let mut pass = ctx
                .encoder
                .begin_compute_pass(&wgpu::ComputePassDescriptor {
                    label: Some("generated skybox roughness prefilter"),
                    timestamp_writes: None,
                });
            pass.set_pipeline(&ctx.pipeline.pipeline);
            pass.set_bind_group(0, &bind_group, &[]);
            pass.dispatch_workgroups(dispatch_groups(dst_size), dispatch_groups(dst_size), 6);
        };
        resources.buffers.push(params_buffer);
        resources.bind_groups.push(bind_group);
        resources.texture_views.push(dst_view);
    }
    resources.buffers.push(sky_params_buffer);
}

/// Returns a texture mip edge clamped to one texel.
fn mip_extent(base: u32, mip: u32) -> u32 {
    (base >> mip).max(1)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Returns the generated cubemap face direction used by the WGSL evaluator.
    fn cube_dir_for_test(face: u32, x: u32, y: u32, n: u32) -> [f32; 3] {
        let u = (x as f32 + 0.5) / n as f32;
        let v = (y as f32 + 0.5) / n as f32;
        let dir = match face {
            0 => [1.0, v * -2.0 + 1.0, u * -2.0 + 1.0],
            1 => [-1.0, v * -2.0 + 1.0, u * 2.0 - 1.0],
            2 => [u * 2.0 - 1.0, 1.0, v * 2.0 - 1.0],
            3 => [u * 2.0 - 1.0, -1.0, v * -2.0 + 1.0],
            4 => [u * 2.0 - 1.0, v * -2.0 + 1.0, 1.0],
            _ => [u * -2.0 + 1.0, v * -2.0 + 1.0, -1.0],
        };
        normalize_for_test(dir)
    }

    /// Normalizes a three-component test vector.
    fn normalize_for_test(v: [f32; 3]) -> [f32; 3] {
        let len = (v[0] * v[0] + v[1] * v[1] + v[2] * v[2]).sqrt();
        [v[0] / len, v[1] / len, v[2] / len]
    }

    /// Returns true when two test vectors are component-wise close.
    fn vectors_close_for_test(a: [f32; 3], b: [f32; 3]) -> bool {
        a.iter().zip(b).all(|(lhs, rhs)| (*lhs - rhs).abs() < 1e-6)
    }

    /// Verifies mip count includes mip zero through the one-texel mip.
    #[test]
    fn mip_levels_for_edge_includes_tail_mip() {
        assert_eq!(mip_levels_for_edge(1), 1);
        assert_eq!(mip_levels_for_edge(2), 2);
        assert_eq!(mip_levels_for_edge(128), 8);
    }

    /// Verifies generated source hashes include material and face-size identity.
    #[test]
    fn generated_key_hash_changes_with_face_size() {
        let a = GeneratedSkyboxKey {
            material_asset_id: 1,
            material_generation: 2,
            route_hash: 3,
            face_size: 128,
        };
        let b = GeneratedSkyboxKey { face_size: 64, ..a };
        assert_ne!(a.source_hash(), b.source_hash());
    }

    /// Verifies generated environments do not inherit point/repeat defaults.
    #[test]
    fn generated_environment_sampler_is_trilinear_clamp() {
        let sampler = generated_environment_sampler_state();
        assert_eq!(sampler.filter_mode, TextureFilterMode::Trilinear);
        assert_eq!(sampler.wrap_u, TextureWrapMode::Clamp);
        assert_eq!(sampler.wrap_v, TextureWrapMode::Clamp);
        assert_eq!(sampler.aniso_level, 1);
    }

    /// Verifies generated cubemap face centers use the intended axis convention.
    #[test]
    fn generated_cube_face_centers_match_axes() {
        let axes = [
            [1.0, 0.0, 0.0],
            [-1.0, 0.0, 0.0],
            [0.0, 1.0, 0.0],
            [0.0, -1.0, 0.0],
            [0.0, 0.0, 1.0],
            [0.0, 0.0, -1.0],
        ];
        for (face, axis) in axes.into_iter().enumerate() {
            assert!(vectors_close_for_test(
                cube_dir_for_test(face as u32, 0, 0, 1),
                axis
            ));
        }
    }

    /// Verifies face-corner signs stay stable for cubemap bake orientation.
    #[test]
    fn generated_cube_face_corners_keep_expected_signs() {
        assert_eq!(
            cube_dir_for_test(0, 0, 0, 2).map(f32::signum),
            [1.0, 1.0, 1.0]
        );
        assert_eq!(
            cube_dir_for_test(1, 0, 0, 2).map(f32::signum),
            [-1.0, 1.0, -1.0]
        );
        assert_eq!(
            cube_dir_for_test(5, 0, 0, 2).map(f32::signum),
            [1.0, 1.0, -1.0]
        );
    }
}
